"""added img do posts

Revision ID: 426ec5edf22d
Revises: 23bac981f133
Create Date: 2023-01-13 13:08:46.708587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426ec5edf22d'
down_revision = '23bac981f133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_pic', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('post_pic')

    # ### end Alembic commands ###
