"""added password field

Revision ID: 795a90762873
Revises: 9969f31c79c6
Create Date: 2023-01-08 15:19:27.308610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795a90762873'
down_revision = '9969f31c79c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
